version: "3.7"
services:
  db:
    image: 'postgres'
    container_name: postgres
    environment:
      # DATABASE_HOST: 127.0.0.1
      # POSTGRES_DB: library
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: '123456'
      # PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - data:/var/lib/postgresql/data
      
    # ports:
    #   - "4321:5421"
    # networks:
    #   postgres:
    #     ipv4_adress: "178.57.55.184"
    restart: always
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports: 
      - "5042:5042"
    depends_on:
      - db
    container_name: server
    command: npm run dev
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    container_name: client
    command: npm start


